In [1]:
import numpy as np

In [2]:
# Tạo mảng
a = np.array([1,2,3])

# In mảng
print(a)

# In ra 1 phần tử
element = a[1]
print(element)

[1 2 3]
2


In [3]:
# Tạo mảng 2 chiều
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)

# In một phần tử
element = matrix[1, 2]
print(element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [4]:
# Cách tạo mảng
# Tạo mảng toàn là số 0
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [5]:
# Tạo mảng toàn là số 1
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [6]:
# Tạo mảng
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [7]:
# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [10]:
# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
a

array([1, 1, 1, 1, 1], dtype=int64)

In [11]:
# Thêm, xóa, sắp xếp mảng
# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

[3 1 2 4 5]


In [12]:
# Sắp xếp
arr = np.sort(arr)
print(arr)

[1 2 3 4 5]


In [13]:
# Sắp xếp ngược
arr = np.sort(arr)[::-1]
print(arr)

[5 4 3 2 1]


In [14]:
# Thêm phần tử vào mảng
arr = np.append(arr, 100)
print(arr)

[  5   4   3   2   1 100]
